#!/bin/sh /etc/rc.common

START=99

start() {
	echo "iot_event_loop start" > /tmp/app.log
	/usr/bin/iot_event_loop &

	#echo "evergrande app start" > /tmp/app.log
	#/usr/bin/zigbee-mgmt &
}

stop() {
	#killall -9 zigbee-mgmt
}
